name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gera a cobrinha SVG
        uses: Platane/snk@master
        with:
          github_user_name: Kaueneto
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit do SVG gerado
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
